
[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "zig"
auto-format = false

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "markdown"
file-types = ["md"]
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
soft-wrap.max-wrap = 100
text-width = 100
language-servers = ["typos"]

[[language]]
name = "typst"
scope = "source.typst"
file-types = ["typ"]
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
soft-wrap.max-wrap = 100
text-width = 100
language-servers = ["tinymist", "typos"]

[[language]]
name = "latex"
scope = "source.latex"
file-types = ["tex"]
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
soft-wrap.max-wrap = 100
text-width = 100
language-servers = ["texlab", "typos"]

[[language]]
name = "verilog"
scope = "source.verilog"
file-types = ["sv", "svh", "v", "vh", "vg"]
indent = { tab-width = 2, unit = "  " }

[language-server.tinymist]
command = "tinymist"
config.preview.background.enabled = true
config.preview.background.args = [
  "--data-plane-host=127.0.0.1:0", "--invert-colors=never", "--open"]

[language-server.typos]
command = "typos-lsp"
environment = {"RUST_LOG" = "error"}
config.config = "~/code/typos-lsp/crates/typos-lsp/tests/typos.toml"
config.diagnosticSeverity = "Info"

[language-server.texlab]
command = "texlab"

[language-server.texlab.config.texlab.build]
onSave = true
forwardSearchAfter = true
executable = "latexmk"
args = [
  "-lualatex", 
  "-interaction=nonstopmode", 
  "-synctex=1", 
  "-shell-escape", 
  "%f"
]

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:%c:%f", "%p" ]

[language-server.texlab.config.texlab.chktex]
onOpenAndSave = true
onEdit = true
