[bar.default]
margin_ends = 0
radius = 0
widget_spacing = 8

[calendar]
enabled = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 10

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 180.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 300.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 200.0

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 957.3333740234375
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
polkit_agent = true

    [shell.animation]
    speed = 2.0000000298023224

[theme]
builtin = "Rosé Pine"
community_palette = "Nord Aurora"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "helix", "hyprland", "kitty", "qt", "sway" ]
    community_ids = [ "pywalfox", "tmux", "yazi" ]

        [theme.templates.user.foot]
        input_path = "./templates/foot/foot"
        output_path = "$XDG_CONFIG_HOME/foot/themes/noctalia"
        post_hook = "bash '{{ config_dir }}/templates/foot/apply.sh' {{ mode }}"
        undo_hook = "bash '{{ config_dir }}/templates/foot/undo.sh'"

[wallpaper]
directory = "/home/joel/Pictures/wallpapers/"
directory_dark = "/home/joel/Pictures/wallpapers/dark"
directory_light = "/home/joel/Pictures/wallpapers/light"

    [wallpaper.default]
    path = "/home/joel/Pictures/wallpapers/dark/rose-pine.png"

    [wallpaper.last]
    path = "/home/joel/Pictures/wallpapers/dark/rose-pine.png"

    [wallpaper.monitors.DP-1]
    path = "/home/joel/Pictures/wallpapers/dark/ylia.webp"

    [wallpaper.monitors.DP-2]
    path = "/home/joel/Pictures/wallpapers/dark/ylia.webp"

    [wallpaper.monitors.eDP-1]
    path = "/home/joel/Pictures/wallpapers/dark/rose-pine.png"
