#!/usr/bin/env bash

# dmenu theming
lines="-l 20"

selected="$(ps -a -u $USER | \
            rofi -dmenu -i -p "Process:" $lines | \
            awk '{print $1" "$4}')"; 

if [[ ! -z $selected ]]; then
    answer="$(echo -e "Yes\nNo" | \
            rofi -dmenu -i -p "Kill $selected?" -l 2)"
    if [[ $answer == "Yes" ]]; then
        selpid="$(awk '{print $1}' <<< $selected)"; 
        kill -9 $selpid
    fi
fi

exit 0
